#!/bin/bash

echo "

CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUDNAME
CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET

DB_CONNECT_STRING=mongodb+srv://$DB_USER:$DB_PASSWD@$DB_CONNECT_STRING?retryWrites=true&w=majority
PORT=4000

FE_SOCKET_CORS=ws://localhost:3010

CLOUDKARAFKA_TOPIC_PREFIX=$DEV_TOPIC_PREFIX
CLOUDKARAFKA_BROKERS=$DEV_KARAFKA_BROKERS
CLOUDKARAFKA_USERNAME=$DEV_KARAFKA_USERNAME
CLOUDKARAFKA_PASSWORD=$DEV_KARAFKA_PASSWORD

MAILER_PASS=$MAILER_PASS

TINYMCEKEY=$TINY_MCE_KEY

TWILIO_ACCT_SID=$TWILIO_SID
TWILIO_ACCT_TOKEN=$TWILIO_AUTH_TOKEN

VIMEO_ACCESS_TOKEN=$VIMEO_ACCESS_TOKEN
" > .env